# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-10 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, unique=True, verbose_name='用户名称')),
                ('password', models.CharField(max_length=256, verbose_name='用户密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='用户邮箱')),
                ('sex', models.CharField(choices=[('male', '男'), ('male', '女')], default='男', max_length=32, verbose_name='用户性别')),
                ('user_num', models.CharField(max_length=128, unique=True, verbose_name='用户序列号')),
                ('live_place', models.CharField(max_length=64, verbose_name='用户住址')),
                ('phone', models.CharField(max_length=64, verbose_name='用户电话')),
                ('birthday', models.CharField(max_length=64, verbose_name='用户生日')),
                ('status', models.SmallIntegerField(choices=[(0, '在线'), (1, '下线'), (2, '空闲'), (3, '忙碌')], default=0, verbose_name='用户状态')),
                ('user_type', models.CharField(choices=[('passenger', '乘客')], default='passenger', max_length=64, verbose_name='用户类型')),
                ('order_num', models.CharField(max_length=64, verbose_name='订单号')),
            ],
            options={
                'verbose_name': '乘客',
                'verbose_name_plural': '乘客',
            },
        ),
    ]
